"""
PostgreSQL database backend with SQL-accelerated filter overloads.

The Connection and Cursor classes here are adapted from the PostgreSQL
addon (addons-source/PostgreSQL/postgresql.py) so that this file is
self-contained and does not require the PostgreSQL addon to be installed.
The _hack_query translation layer is retained so that Gramps core DBAPI
queries (which use SQLite-style '?' placeholders) continue to work.
Our own filter SQL is written using PostgreSQL-native syntax via
sql_compat.SQLCompat and therefore bypasses _hack_query automatically.

Shared code (overload_rules, sql_compat) is provided by FastFiltersLib,
a load_on_reg GENERAL plugin that must be installed alongside this addon.
"""

import os
import re

import psycopg2

from gramps.plugins.db.dbapi.dbapi import DBAPI
from gramps.gen.utils.configmanager import ConfigManager
from gramps.gen.config import config
from gramps.gen.db.dbconst import ARRAYSIZE
from gramps.gen.db.exceptions import DbConnectionError
from gramps.gen.const import GRAMPS_LOCALE as glocale
from fastfilterslib.overload_rules import register_rules

try:
    _trans = glocale.get_addon_translator(__file__)
except ValueError:
    _trans = glocale.translation
_ = _trans.gettext

psycopg2.paramstyle = "format"


# ---------------------------------------------------------------------------
# PostgreSQLFastFilters
# ---------------------------------------------------------------------------


class PostgreSQLFastFilters(DBAPI):
    dialect = "postgresql"

    def get_summary(self):
        summary = super().get_summary()
        summary.update(
            {
                _("Database version"): psycopg2.__version__,
                _("Database module location"): psycopg2.__file__,
            }
        )
        return summary

    def requires_login(self):
        return True

    def _initialize(self, directory, username, password):
        config_file = os.path.join(directory, "settings.ini")
        config_mgr = ConfigManager(config_file)
        config_mgr.register("database.dbname", "")
        config_mgr.register("database.host", "")
        config_mgr.register("database.port", "")

        if not os.path.exists(config_file):
            name_file = os.path.join(directory, "name.txt")
            with open(name_file, "r", encoding="utf8") as fh:
                dbname = fh.readline().strip()
            config_mgr.set("database.dbname", dbname)
            config_mgr.set("database.host", config.get("database.host"))
            config_mgr.set("database.port", config.get("database.port"))
            config_mgr.save()

        config_mgr.load()

        dbkwargs = {}
        for key in config_mgr.get_section_settings("database"):
            value = config_mgr.get("database." + key)
            if value:
                dbkwargs[key] = value
        if username:
            dbkwargs["user"] = username
        if password:
            dbkwargs["password"] = password

        try:
            self.dbapi = _Connection(**dbkwargs)
        except psycopg2.OperationalError as exc:
            raise DbConnectionError(str(exc), config_file) from exc

        register_rules(self)


# ---------------------------------------------------------------------------
# Connection
# ---------------------------------------------------------------------------


class _Connection:
    """
    Thin wrapper around a psycopg2 connection.

    Translates SQLite-style queries used internally by the Gramps DBAPI
    layer into PostgreSQL syntax via _hack_query, mirroring the logic in
    the standard PostgreSQL addon.
    """

    def __init__(self, *args, **kwargs):
        self.__connection = psycopg2.connect(*args, **kwargs)
        self.__connection.autocommit = True
        self.__cursor = self.__connection.cursor()
        self.check_collation(glocale)

    def check_collation(self, locale):
        """Create the locale collation in PostgreSQL if it does not exist."""
        collation = locale.get_collation()
        self.__cursor.execute(
            'CREATE COLLATION IF NOT EXISTS "%s" (LOCALE = \'%s\')'
            % (collation, locale.collation)
        )

    @staticmethod
    def _hack_query(query):
        """Translate SQLite-style SQL fragments to PostgreSQL syntax.

        This covers the internal Gramps DBAPI queries which are written
        against SQLite conventions.  Filter SQL generated by sql_compat
        is already PostgreSQL-native and is not affected by these rules.
        """
        query = query.replace("?", "%s")
        query = query.replace("REGEXP", "~")
        query = query.replace("BLOB", "bytea")
        # SQLite: LIMIT -1 means "no limit"
        query = query.replace("LIMIT -1", "LIMIT all")
        # SQLite: LIMIT offset, count  →  PostgreSQL: LIMIT count OFFSET offset
        match = re.match(r".* LIMIT (.*), (.*) ", query)
        if match:
            offset, count = match.groups()
            if count == "-1":
                count = "all"
            query = re.sub(
                r"(.*) LIMIT (.*), (.*) ",
                r"\1 LIMIT %s OFFSET %s " % (count, offset),
                query,
            )
        return query

    def execute(self, *args, **kwargs):
        sql = self._hack_query(args[0])
        params = args[1] if len(args) > 1 else None
        try:
            self.__cursor.execute(sql, params, **kwargs)
        except Exception:
            self.__cursor.execute("rollback")
            raise

    def fetchone(self):
        try:
            return self.__cursor.fetchone()
        except Exception:
            return None

    def fetchall(self):
        return self.__cursor.fetchall()

    def begin(self):
        self.__cursor.execute("BEGIN;")

    def commit(self):
        self.__cursor.execute("COMMIT;")

    def rollback(self):
        self.__connection.rollback()

    def table_exists(self, table):
        self.__cursor.execute(
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_name = %s;",
            [table],
        )
        return self.fetchone()[0] != 0

    def column_exists(self, table, column):
        self.__cursor.execute(
            "SELECT COUNT(*) FROM information_schema.columns "
            "WHERE table_name = %s AND column_name = %s",
            (table, column),
        )
        return self.fetchone()[0] != 0

    def drop_column(self, table_name, column_name):
        self.execute(f"ALTER TABLE {table_name} DROP COLUMN {column_name};")

    def close(self):
        self.__connection.close()

    def cursor(self):
        return _Cursor(self.__connection)


# ---------------------------------------------------------------------------
# Cursor
# ---------------------------------------------------------------------------


class _Cursor:
    """Context-manager cursor for bulk reads."""

    def __init__(self, connection):
        self.__connection = connection

    def __enter__(self):
        self.__cursor = self.__connection.cursor()
        self.__cursor.arraysize = ARRAYSIZE
        return self

    def __exit__(self, *args, **kwargs):
        self.__cursor.close()

    def execute(self, *args, **kwargs):
        self.__cursor.execute(*args, **kwargs)

    def fetchone(self):
        try:
            return self.__cursor.fetchone()
        except Exception:
            return None

    def fetchmany(self):
        try:
            return self.__cursor.fetchmany()
        except Exception:
            return None
